#!/usr/bin/env python3
"""
Intermediate Results Cleaner for NL2X Project

This script helps clean up intermediate result directories created by the baseline systems.
It supports cleaning specific directories, baseline-specific results, or all intermediate files.
"""

import os
import sys
import argparse
import shutil
from pathlib import Path
from typing import List, Set


class IntermediateResultsCleaner:
    """Cleaner for intermediate results generated by baseline systems."""

    def __init__(self, project_root: str = None):
        """Initialize the cleaner with the project root directory."""
        if project_root is None:
            project_root = os.path.dirname(os.path.abspath(__file__))
        self.project_root = Path(project_root)

        # Define the intermediate result directories
        self.intermediate_dirs = {
            'converted_data': self.project_root / 'converted_data',
            'generated_pipelines': self.project_root / 'generated_pipelines',
            'generated_prompts': self.project_root / 'generated_prompts',
            'messages': self.project_root / 'messages',
            'validations': self.project_root / 'validations'
        }

        # Define baseline subdirectories
        self.baselines = ['docetl', 'lotus']

    def get_directories_to_clean(self, dir_types: Set[str], baselines: Set[str]) -> List[Path]:
        """Get list of directories to clean based on selection criteria."""
        dirs_to_clean = []

        for dir_type in dir_types:
            if dir_type not in self.intermediate_dirs:
                continue

            base_dir = self.intermediate_dirs[dir_type]
            if not base_dir.exists():
                continue

            if baselines:
                # Clean specific baseline subdirectories
                for baseline in baselines:
                    baseline_dir = base_dir / baseline
                    if baseline_dir.exists():
                        dirs_to_clean.append(baseline_dir)
            else:
                # Clean all baseline subdirectories in this dir_type
                for baseline in self.baselines:
                    baseline_dir = base_dir / baseline
                    if baseline_dir.exists():
                        dirs_to_clean.append(baseline_dir)

        return dirs_to_clean

    def get_files_in_directory(self, directory: Path) -> List[Path]:
        """Get all files in a directory recursively."""
        files = []
        if directory.exists() and directory.is_dir():
            for item in directory.rglob('*'):
                if item.is_file():
                    files.append(item)
        return files

    def clean_directory(self, directory: Path, dry_run: bool = False, verbose: bool = False) -> int:
        """Clean a single directory and return number of files deleted."""
        if not directory.exists():
            if verbose:
                print(f"Directory does not exist: {directory}")
            return 0

        files = self.get_files_in_directory(directory)

        if dry_run:
            if verbose:
                print(f"Would delete {len(files)} files from: {directory}")
                for file_path in files[:10]:  # Show first 10 files
                    print(f"  - {file_path}")
                if len(files) > 10:
                    print(f"  ... and {len(files) - 10} more files")
            return len(files)

        # Actually delete the files
        deleted_count = 0
        try:
            if directory.is_dir():
                shutil.rmtree(directory)
                # Recreate empty directory
                directory.mkdir(parents=True, exist_ok=True)
                deleted_count = len(files)
                if verbose:
                    print(f"Cleaned {deleted_count} files from: {directory}")
        except Exception as e:
            print(f"Error cleaning {directory}: {e}", file=sys.stderr)
            return 0

        return deleted_count

    def confirm_deletion(self, dirs_to_clean: List[Path], total_files: int) -> bool:
        """Ask user for confirmation before deletion."""
        print(f"\nThe following directories will be cleaned:")
        for directory in dirs_to_clean:
            file_count = len(self.get_files_in_directory(directory))
            print(f"  - {directory} ({file_count} files)")

        print(f"\nTotal files to be deleted: {total_files}")

        while True:
            response = input("\nDo you want to proceed? (y/N): ").strip().lower()
            if response in ['y', 'yes']:
                return True
            elif response in ['n', 'no', '']:
                return False
            else:
                print("Please enter 'y' for yes or 'n' for no.")

    def clean(self, dir_types: Set[str], baselines: Set[str] = None,
              dry_run: bool = False, force: bool = False, verbose: bool = False) -> int:
        """
        Clean intermediate result directories.

        Args:
            dir_types: Set of directory types to clean
            baselines: Set of baselines to clean (None for all)
            dry_run: If True, only show what would be deleted
            force: If True, skip confirmation prompt
            verbose: If True, show detailed output

        Returns:
            Number of files deleted (or would be deleted in dry-run)
        """
        if baselines is None:
            baselines = set()

        dirs_to_clean = self.get_directories_to_clean(dir_types, baselines)

        if not dirs_to_clean:
            print("No directories found to clean.")
            return 0

        # Count total files
        total_files = sum(len(self.get_files_in_directory(d)) for d in dirs_to_clean)

        if total_files == 0:
            print("No files found to clean.")
            return 0

        # Show what will be cleaned
        if dry_run or verbose:
            action = "Would clean" if dry_run else "Will clean"
            print(f"{action} {len(dirs_to_clean)} directories with {total_files} total files.")

        # Ask for confirmation unless forced or dry run
        if not dry_run and not force:
            if not self.confirm_deletion(dirs_to_clean, total_files):
                print("Cleaning cancelled.")
                return 0

        # Perform the cleaning
        total_deleted = 0
        for directory in dirs_to_clean:
            deleted = self.clean_directory(directory, dry_run, verbose)
            total_deleted += deleted

        if dry_run:
            print(f"\nDry run completed. Would delete {total_deleted} files.")
        else:
            print(f"\nCleaning completed. Deleted {total_deleted} files.")

        return total_deleted


def main():
    """Main entry point for the cleaner script."""
    parser = argparse.ArgumentParser(
        description="Clean intermediate result directories from NL2X baseline runs",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s --converted_data --docetl        # Clean only DocETL converted data
  %(prog)s --all --force                    # Clean everything without confirmation
  %(prog)s --generated_pipelines --dry-run  # Show what pipeline files would be deleted
  %(prog)s --messages --validations         # Clean message and validation files for all baselines
        """
    )

    # Directory type options
    parser.add_argument('--converted_data', action='store_true',
                       help='Clean converted data files')
    parser.add_argument('--generated_pipelines', action='store_true',
                       help='Clean generated pipeline files')
    parser.add_argument('--generated_prompts', action='store_true',
                       help='Clean generated prompt files')
    parser.add_argument('--messages', action='store_true',
                       help='Clean message history files')
    parser.add_argument('--validations', action='store_true',
                       help='Clean validation result files')
    parser.add_argument('--all', action='store_true',
                       help='Clean all intermediate result directories')

    # Baseline-specific options
    parser.add_argument('--docetl', action='store_true',
                       help='Clean only DocETL-related files')
    parser.add_argument('--lotus', action='store_true',
                       help='Clean only Lotus-related files')

    # Control options
    parser.add_argument('--dry-run', action='store_true',
                       help='Show what would be deleted without actually deleting')
    parser.add_argument('--force', action='store_true',
                       help='Skip confirmation prompt')
    parser.add_argument('--verbose', '-v', action='store_true',
                       help='Show detailed output')

    args = parser.parse_args()

    # Determine which directory types to clean
    dir_types = set()
    if args.all:
        dir_types = {'converted_data', 'generated_pipelines', 'generated_prompts', 'messages', 'validations'}
    else:
        if args.converted_data:
            dir_types.add('converted_data')
        if args.generated_pipelines:
            dir_types.add('generated_pipelines')
        if args.generated_prompts:
            dir_types.add('generated_prompts')
        if args.messages:
            dir_types.add('messages')
        if args.validations:
            dir_types.add('validations')

    if not dir_types:
        parser.error("No directory types specified. Use --all or specify individual directory types.")

    # Determine which baselines to clean
    baselines = set()
    if args.docetl:
        baselines.add('docetl')
    if args.lotus:
        baselines.add('lotus')

    # Create cleaner and run
    cleaner = IntermediateResultsCleaner()

    try:
        total_deleted = cleaner.clean(
            dir_types=dir_types,
            baselines=baselines if baselines else None,
            dry_run=args.dry_run,
            force=args.force,
            verbose=args.verbose
        )

        return 0 if total_deleted >= 0 else 1

    except KeyboardInterrupt:
        print("\nCleaning interrupted by user.")
        return 1
    except Exception as e:
        print(f"Error during cleaning: {e}", file=sys.stderr)
        return 1


if __name__ == '__main__':
    sys.exit(main())