"""
Abstract Layer Prompts
"""

from string import Template
from ..abstract.support import BaseSystem, format_operators_with_descriptions
from .instructions import get_operator_selection_rules
from typing import List, Dict, Any
import json


# =============================================================================
# Detailed Operator Configuration Prompts
# =============================================================================

ABSTRACT_MAP_PROMPT = Template("""
Generate a Map operator configuration in abstract layer format.

A Map operator transforms EACH record independently using an LLM (1-to-1 mapping). It analyzes, summarizes, or transforms data to generate new fields. Unlike Extract, Map does NOT pull verbatim text - it performs transformations (e.g., sentiment analysis, summarization, structured extraction from analysis).

Context:
- Query: $query
- Operator Task: $operator_purpose

Available Fields (with types):
$available_fields

Current Pipeline:
$current_pipeline

Dataset Samples:
$dataset_samples

Generate a Map operator with:

1. **prompt**: A Jinja2 template string that describes the transformation
   - CRITICAL: MUST use {{ input.field_name }} to reference ALL input fields
   - Be specific about what to extract or transform
   - For each field to be output, explain the meaning of it, for example, "medication: the medication contained in the doctor's prescription in the document" is better than "medication".

2. **output**: Specify output schema as {"field1": "Type1", "field2": "Type2", ...}
   - ONLY add NEW fields generated by this operator
   - Input fields are automatically carried forward, so only list the fields you CREATE
   - Type specifications: String, Integer, Float, Boolean, List[Type], Dict{field: Type}
   - Examples: {"sentiment": "String", "scores": "List[Integer]", "metadata": "Dict{count: Integer}"}

COMPLETE EXAMPLES:

Example - Extracting structured data:
{
  "prompt": "Analyze the text: {{ input.content }}. Extract the main themes discussed. Return a list of theme names.",
  "output": {
    "themes": "List[String]",
    "summary": "String"
  },
}

IMPORTANT:
- Use ONLY available fields in input
- Make prompts specific to the task, not generic
- ALWAYS use Jinja2 format for field references: {{ input.field_name }}
""")

ABSTRACT_FILTER_PROMPT = Template("""
Generate a Filter operator configuration in abstract layer format.

A Filter operator keeps or discards records based on a condition.

Context:
- Query: $query
- Operator Task: $operator_purpose

Available Fields (with types):
$available_fields

Current Pipeline:
$current_pipeline

Dataset Samples:
$dataset_samples

Generate a Filter operator with:

1. **prompt**: A Jinja2 template that describes the filtering condition
   - MUST use {{ input.field_name }} to reference fields (Jinja2 template)
   - CRITICAL: MUST use fields from the available fields list
   - The prompt should ask for "true" or "false" as the response
   - Clearly state what records should PASS the filter (return true to keep)
   - Example: "Is this relevant? {{ input.title }}. Return true to keep, false to discard."

2. **input**: Specify input schema
   - {"fields": {"field1": "Type1", ...}}
   - Only include fields used in the condition
   - Example: {"fields": {"score": "Float"}}

3. **output**: Specify output schema
   - MUST include a Boolean field for the filter decision
   - Input fields are automatically carried forward, so only list the fields you CREATE
   - Type specifications: String, Integer, Float, Boolean, List[Type], Dict{field: Type}
   - Example: {"id": "Integer", "text": "String", "score": "Float", "keep": "Boolean"}

4. **properties**: Additional configuration (can be empty {})

COMPLETE EXAMPLES:

Example - Filter by relevance:
{
  "prompt": "Is this document relevant to the topic? Title: {{ input.title }}. Content: {{ input.content }}. Return true to keep this document, false to discard it.",
  "input": {"fields": {"title": "String", "content": "String"}},
  "output": {
    "title": "String",
    "content": "String",
    "keep": "Boolean"
  },
  "properties": {}
}

IMPORTANT:
- The output schema MUST have a Boolean field
- Make the filtering condition clear and specific
""")

ABSTRACT_REDUCE_PROMPT = Template("""
Generate a Reduce operator configuration in abstract layer format.

A Reduce operator aggregates/groups records by a key field.

Context:
- Query: $query
- Operator Task: $operator_purpose

Available Fields (with types):
$available_fields

Current Pipeline:
$current_pipeline

Dataset Samples:
$dataset_samples

Generate a Reduce operator with:

1. **reduce_key**: The field to group by (must exist in available fields)
   - Example: "category" (if grouping by category)

2. **prompt**: Jinja2 template describing how to aggregate
   - MUST use {{ inputs }} (plural) to reference the group of records (Jinja2 template)
   - Access fields like: {{ inputs[0].field_name }} or {% for item in inputs %}{{ item.field_name }}{% endfor %}
   - Example: "Summarize all viewpoints for theme '{{ inputs[0].theme }}': {% for item in inputs %}{{ item.viewpoint }} {% endfor %}"

3. **output**: Specify output schema
   - MUST include the reduce_key field
   - Add new aggregated fields
   - Type specifications: String, Integer, Float, Boolean, List[Type], Dict{field: Type}
   - Examples: {"category": "String", "summary": "String", "count": "Integer", "items": "List[String]"}

COMPLETE EXAMPLES:

Example - Aggregate reviews by product:
{
  "reduce_key": "product_id",
  "prompt": "Product: {{ inputs[0].product_name }}. Reviews: {% for review in inputs %}{{ review.text }}. {% endfor %}Provide: product_name: the name of the product; common_themes: a list of common themes mentioned across reviews; average_sentiment: the overall average sentiment (positive/negative/neutral).",
  "output": {
    "product_id": "String",
    "product_name": "String",
    "common_themes": "List[String]",
    "average_sentiment": "String"
  },
}

IMPORTANT:
- You MUST use {{ inputs }} (plural) to reference the group of records
- Use ONLY available fields in input
- Create aggregated output schema with new field names
""")

ABSTRACT_RESOLVE_PROMPT = Template("""
Generate a Resolve operator configuration in abstract layer format.

A Resolve operator deduplicates or standardizes entities using comparison and resolution prompts.

Context:
- Query: $query
- Operator Task: $operator_purpose

Available Fields (with types):
$available_fields

Current Pipeline:
$current_pipeline

Dataset Samples:
$dataset_samples

Generate a Resolve operator with:

1. **comparison_prompt**: Jinja2 template for comparing two records
   - Uses {{ input1.field }} and {{ input2.field }} to compare two items
   - Should return "True" or "False"
   - Example: "Are {{ input1.patient_name }} and {{ input2.patient_name }} the same patient? Return True or False."

2. **resolution_prompt**: Jinja2 template for merging records
   - Uses {{ inputs }} to merge multiple similar items
   - Describe how to create one standardized/merged record
   - Example: "Merge these patient records: {% for item in inputs %}{{ item.patient_name }} {% endfor %} Output a single, standardized patient name that represents all the matched entries. Use the format 'LastName, FirstName MiddleInitial' if available."

3. **output**: Specify output schema (resolved/standardized entity schema)
   - Type specifications: String, Integer, Float, Boolean, List[Type], Dict{field: Type}
   - Create output schema for the resolved/standardized entity
   - The output schema adds new fields with standardized values to all records identified as the same entity, overriding original values. CRITICAL: Only include fields that require standardization (e.g., canonical entity names, IDs). DO NOT include fields with legitimate variations that should be preserved, such as:
     * Multiple valid email addresses for the same person
     * Different functions/features of the same tool
     * Time-varying attributes (timestamps)
     * Context-specific descriptions
     * Any other fields that are unique to each record or might vary significantly between records
    Including such fields will cause SEVERE data loss by replacing all variations with a single value.

COMPLETE EXAMPLES:

Example - Resolve duplicate patient names:
{
  "comparison_prompt": "Compare the following two patient name entries:
    Patient 1: {{ input1.patient_name }}
    Date of Birth 1: {{ input1.date_of_birth }}

    Patient 2: {{ input2.patient_name }}
    Date of Birth 2: {{ input2.date_of_birth }}

    Are these entries likely referring to the same patient? Consider name similarity and date of birth. Respond with "True" if they are likely the same patient, or "False" if they are likely different patients.",
  "resolution_prompt": "Standardize the following patient name entries into a single, consistent format:

    {% for entry in inputs %}
    Patient Name {{ loop.index }}: {{ entry.patient_name }}
    {% endfor %}

    Provide a single, standardized patient name that represents all the matched entries. Use the format "LastName, FirstName MiddleInitial" if available.",
  "output": {
    "patient_name": "String"
   },
}
This example doesn't include `email` in the output schema because the person might have multiple email addresses, and we want to keep the original email addresses.

IMPORTANT:
- Use ONLY available fields in input
""")

ABSTRACT_EXTRACT_PROMPT = Template("""
Generate an Extract operator configuration in abstract layer format.

An Extract operator pulls verbatim text sections from documents. It extracts exact quotes, specific text spans, or passages without transformation - the output is the original text as-is.

CRITICAL EXTRACT OPERATOR RULES:
- Extract can ONLY output a SINGLE string field containing the extracted text for each document_key
- Extract is NOT applicable for tasks needing analysis, transformation, or multiple output fields

Context:
- Query: $query
- Operator Task: $operator_purpose

Available Fields (with types):
$available_fields

Current Pipeline:
$current_pipeline

Dataset Samples:
$dataset_samples

Generate an Extract operator with:

1. **prompt**: Jinja2 template describing what text section to extract
   - Use {{ input.field }} to reference the document field (Jinja2 template)
2. **document_keys**: List of field names containing the documents to extract from.

EXTRACT LOGIC (Pseudo-Python):

```python
def extract(records, prompt, document_keys):
    \"\"\"
    Extract operator internal logic:
    - Processes each record independently
    - For each document_key, extracts verbatim text using LLM
    - Creates new field with extracted content (document_key + "_extracted_findings")
    - Returns records with extracted text added as new fields
    \"\"\"
    result = []

    for record in records:
        new_record = record.copy()

        # Process each document key specified
        for doc_key in document_keys:
            if doc_key not in record:
                continue

            # Get the text content from the document field
            document_text = record[doc_key]

            # Render the extraction prompt with record data in strict Jinja2 template format.
            # Example: "Extract findings from: {{ input.content }}"
            rendered_prompt = render_template(prompt, {"input": record})

            # Use LLM to identify and extract verbatim text sections
            # LLM analyzes the document and returns exact text spans
            extracted_text = llm_extract(
                instructions=rendered_prompt,
                source_text=document_text
            )

            # Store extracted text in new field (original field + "_extracted_findings")
            output_field = f"{doc_key}_extracted_findings"
            new_record[output_field] = extracted_text  # Verbatim text

        result.append(new_record)

    return result
```

IMPORTANT:
- Use ONLY available fields in input
""")

ABSTRACT_UNNEST_PROMPT = Template("""
Generate an Unnest operator configuration.

An Unnest operator expands arrays or nested fields. The target of Unnest is to flatten the array or nested structure into simple types.

Context:
- Query: $query
- Operator Task: $operator_purpose

Available Fields (with types):
$available_fields

Current Pipeline:
$current_pipeline

Dataset Samples:
$dataset_samples

Generate an Unnest operator with:

1. **unnest_key**: The field name containing the array or nested structure to expand
   - Must be a field that exists in available fields
   - Should be a Complex type field (e.g., "List[...]]", "Dict{...}")
2. **recursive**: Whether to recursively unnest nested structures. It's useful for flattening multi-level arrays or dicts such as "List[Dict{...}]".

UNNEST LOGIC (Pseudo-Python):

```python
def unnest(records, unnest_key, recursive=False, depth=0):
    \"\"\"
    Unnest operator internal logic:
    - If unnest_key is List: expands into multiple records (one per element)
    - If unnest_key is Dict: flattens fields to top level (same number of records)
    - If recursive=True: applies unnesting recursively
    \"\"\"
    result = []
    
    for record in records:
        if unnest_key not in record or (not recursive and depth > 0):
            # If unnest_key not found, we can exit from recursion
            return records

        value = record[unnest_key]
        base_record = {k: v for k, v in record.items() if k != unnest_key}

        if isinstance(value, list):
            # List: Create separate record for each element
            for item in value:
                new_record = base_record.copy()
                new_record[unnest_key] = item
                result.append(new_record)

        elif isinstance(value, dict):
            # Dict: Flatten to top level (no new records)
            new_record = base_record.copy()
            new_record.pop(unnest_key, None)
            new_record.update(value)  # Move dict fields to top level
            result.append(new_record)

        else:
            raise ValueError(f"Unnest only supports lists and dicts.")

    # If recursive, apply unnest again
    if recursive:
        result = unnest(result, unnest_key, recursive=True, depth=depth+1)

    return result
```
""")

# Map of operator types to their prompts
OPERATOR_TYPE_TO_PROMPT = {
    'Map': ABSTRACT_MAP_PROMPT,
    'Filter': ABSTRACT_FILTER_PROMPT,
    'Reduce': ABSTRACT_REDUCE_PROMPT,
    'Resolve': ABSTRACT_RESOLVE_PROMPT,
    'Extract': ABSTRACT_EXTRACT_PROMPT,
    'Unnest': ABSTRACT_UNNEST_PROMPT,
    # Additional operators can be added later
}


def get_abstract_operator_prompt(
    operator_type: str,
    operator_purpose: str,
    query: str,
    dataset_samples: str,
    current_pipeline: str,
    available_fields: str
) -> str:
    """
    Get the appropriate prompt based on operator type.

    Args:
        operator_type: Operator type (Map, Filter, etc.)
        operator_purpose: Operator task description
        query: User query
        dataset_samples: Dataset samples
        current_pipeline: Current pipeline in compact format
        available_fields: Available fields (formatted string)

    Returns:
        Complete prompt string

    Raises:
        ValueError: If operator type is not supported
    """
    prompt_template = OPERATOR_TYPE_TO_PROMPT.get(operator_type)

    if prompt_template is None:
        # For operators not yet implemented, return a generic prompt
        return f"""
Generate a {operator_type} operator configuration in abstract layer format.

Context:
- Query: {query}
- Operator Task: {operator_purpose}

Available Fields:
{available_fields}

Current Pipeline:
{current_pipeline}

Dataset Samples:
{dataset_samples}

Please generate appropriate configuration for this {operator_type} operator.
Include: input schema, output schema, and any operator-specific fields.
Return valid JSON.
"""

    return prompt_template.substitute(
        query=query,
        operator_purpose=operator_purpose,
        available_fields=available_fields,
        current_pipeline=current_pipeline,
        dataset_samples=dataset_samples
    )


# =============================================================================
# JIT Step-by-Step: Next Operator Generation
# =============================================================================

NEXT_OPERATOR_PROMPT = Template("""
You are an AI assistant that builds data processing pipelines one operator at a time.

Task: Analyze the current pipeline and determine the NEXT operator type needed, OR decide if the pipeline is complete.

Query: $query

Dataset Structure and Samples:
$dataset_samples

Current Pipeline:
$current_pipeline

Available Fields (with types):
$available_fields

Available Abstract Operators:
$available_operators

IMPORTANT RULES:
$important_rules

Your Task:
1. Analyze the query and current pipeline
2. Determine if the pipeline is COMPLETE (query can be fully answered with current operators)
3. If COMPLETE: Return {"end": true, "reason": "explanation of why pipeline is complete"}
4. If NOT COMPLETE: Select the TYPE and PURPOSE of the NEXT operator needed

For the next operator, provide:
- type: The operator type to use (e.g., "Map", "Filter", "Reduce")
- purpose: Brief description of what this operator will do in the pipeline

Full Pipeline Examples: 

Example 1: Mining Product Reviews for Polarizing Themes
Query: "Identify polarizing themes in video game reviews that divide player opinions, resolve similar themes across reviews, and aggregate them to find common polarizing themes across different games"
Dataset: Video game reviews with fields: app_name, concatenated_reviews

Selected operators and reasoning:
- Map: identify polarizing themes from concatenated reviews (analyzes each game's reviews to find divisive topics)
- Unnest: expand polarizing_themes array into individual theme records (needed to process each theme separately)
- Resolve: deduplicate and consolidate similar themes (merges themes that are essentially the same but worded differently)
- Reduce: aggregate common themes across different games by theme (groups resolved themes to find patterns across games)

Response Format:
Either:
{"end": true, "reason": "Pipeline complete because..."}

OR:
{"end": false, "operator": {"type": "OperatorType", "purpose": "what this operator will do"}}

Remember:
- Stop when the pipeline can fully answer the query
- Each operator should have a clear purpose in the overall pipeline
""")


def get_next_operator_prompt(
    query: str,
    dataset_samples: str,
    current_pipeline: str,
    available_fields: str,
    base_system: BaseSystem
) -> str:
    """
    Generate prompt for JIT next operator selection and configuration.

    Args:
        query: User query
        dataset_samples: Dataset samples (JSON formatted string)
        current_pipeline: Current pipeline in compact format
        available_fields: Available fields (formatted string)
        base_system: Base system type

    Returns:
        Complete prompt string
    """
    operators_info = format_operators_with_descriptions(base_system)
    rules_text = get_operator_selection_rules()

    return NEXT_OPERATOR_PROMPT.substitute(
        query=query,
        dataset_samples=dataset_samples,
        current_pipeline=current_pipeline,
        available_fields=available_fields,
        available_operators=operators_info,
        important_rules=rules_text
    )


# =============================================================================
# JIT Step-by-Step: Operator Repair
# =============================================================================

OPERATOR_REPAIR_PROMPT = Template("""
You are an AI assistant that analyzes validation errors in data processing pipelines and suggests operator repairs.

Query: $query

Current Pipeline:
$current_pipeline

Failed Operator (at position $operator_index):
$failed_operator

Validation Errors:
$validation_errors

Available Fields Before This Operator:
$available_fields

Your Task:
Analyze the validation errors and suggest a NEW operator to replace the failed one.

The new operator can be:
- Same type with corrected configuration (if the operator type is correct)
- Preprocessing operator (e.g., Unnest to flatten arrays, Map to transform data)
- Completely different operator type (if the approach was fundamentally wrong)

Choose whatever operator type best solves the validation errors.

Response Format (JSON):
{
  "analysis": "What went wrong and why",
  "rationale": "How your suggestion fixes the specific errors",
  "new_operator": {
    "type": "operator_type",
    "purpose": "what this operator will do"
  }
}

Guidelines:
- Choose the SIMPLEST fix that addresses the validation error
- If a field is missing, suggest a preprocessing operator (e.g., Unnest, Map) to create it
- If the operator logic is wrong, regenerate it with correct configuration
- If the operator type is fundamentally wrong, suggest a different operator type
- Provide clear rationale explaining how your suggestion fixes the specific validation errors

Examples:
- Missing nested field → Unnest to flatten the structure
- Wrong field type → Map to transform the data
- Wrong operator logic → Same operator type with corrected prompts/schema
- Wrong approach → Different operator type entirely
""")


def get_operator_repair_prompt(
    query: str,
    current_pipeline: str,
    failed_operator: str,
    validation_errors: List[str],
    available_fields: str,
    operator_index: int
) -> str:
    """
    Generate prompt for operator repair analysis.

    Args:
        query: User query
        current_pipeline: Current pipeline state (formatted string)
        failed_operator: Failed operator configuration (JSON string)
        validation_errors: List of validation error messages
        available_fields: Available fields (formatted string)
        operator_index: Index of failed operator

    Returns:
        Complete prompt string
    """
    errors_text = "\n".join(f"- {error}" for error in validation_errors)

    return OPERATOR_REPAIR_PROMPT.substitute(
        query=query,
        current_pipeline=current_pipeline,
        failed_operator=failed_operator,
        validation_errors=errors_text,
        available_fields=available_fields,
        operator_index=operator_index
    )


# =============================================================================
# Formatting Utilities
# =============================================================================

def _get_output_fields(before_schema: Dict[str, str], after_schema: Dict[str, str]) -> List[str]:
    """
    Get fields that were added or modified by an operator.

    Args:
        before_schema: Schema before the operator
        after_schema: Schema after the operator

    Returns:
        List of field names that were added or modified
    """
    output_fields = []

    for field, field_type in after_schema.items():
        # Field is new (added)
        if field not in before_schema:
            output_fields.append(field)
        # Field type was modified
        elif before_schema[field] != field_type:
            output_fields.append(field)

    return sorted(output_fields)


def format_pipeline_compact(
    operators: List,
    initial_schema: Dict[str, str],
) -> str:
    """
    Format operators list in compact schema-flow format.

    Args:
        operators: List of Operator instances
        initial_schema: Initial dataset schema
        schema_tracker: Schema tracker to get input schemas and track schema evolution

    Returns:
        Formatted pipeline string in compact format:
        field1, field2 = Dataset # Initial schema
        out1, out2 = Map(in1, in2) # Purpose: ...
        Filter(field1) # Purpose: ...
    """
    if not operators:
        return "No operators yet (this will be the first operator)"

    from ..abstract.convert.docetl import abstract_to_docetl
    from ..docetl_support.schema_tracking import DocETLSchemaTracker

    lines = []

    # Line 1: Dataset with initial schema
    dataset_fields = ", ".join(sorted(initial_schema.keys()))
    lines.append(f"{dataset_fields} = Dataset # Initial schema")

    # Create a temporary schema tracker to track schema evolution
    temp_tracker = DocETLSchemaTracker(initial_schema=initial_schema, verbose=False)

    # Process each operator
    for idx, op in enumerate(operators):
        # Convert abstract operator to base system format
        base_op = abstract_to_docetl(op)

        # Get schema before this operator
        before_schema = temp_tracker.get_current_schema()

        # Get input fields using tracker's get_input_schema
        input_schema_info = temp_tracker.get_input_schema(base_op)
        input_fields = []
        if "fields" in input_schema_info:
            input_fields = sorted(input_schema_info["fields"].keys())
        input_str = ", ".join(input_fields) if input_fields else ""

        # Update schema with this operator
        temp_tracker.update_schema(base_op)

        # Get schema after this operator
        after_schema = temp_tracker.get_current_schema()

        # Get output fields (added or modified)
        output_fields = _get_output_fields(before_schema, after_schema)

        # Get operator purpose from properties
        purpose = op.properties.get('purpose', '')
        purpose_str = f" # Purpose: {purpose}" if purpose else ""

        # Format the line
        if output_fields:
            # Operator produces outputs: outputs = OperatorType(inputs)
            output_str = ", ".join(output_fields)
            lines.append(f"{idx+1}. {output_str} = {op.type}({input_str}){purpose_str}")
        else:
            # Operator has no outputs: OperatorType(inputs)
            lines.append(f"{idx+1}. {op.type}({input_str}){purpose_str}")

    return "\n".join(lines)


def format_pipeline_state(operators: List) -> str:
    """
    DEPRECATED: Use format_pipeline_compact() instead.

    Format operators list into readable pipeline state.

    Args:
        operators: List of operators

    Returns:
        Formatted pipeline state string
    """
    if not operators:
        return "No operators yet (this will be the first operator)"

    from ..abstract.convert.docetl import operator_to_dict

    pipeline_state_parts = []
    for i, op in enumerate(operators):
        op_dict = operator_to_dict(op)
        pipeline_state_parts.append(f"{i+1}. {op.type} ({op.name}):\n{json.dumps(op_dict, indent=2)}")
    return "\n\n".join(pipeline_state_parts)


def format_repair_context(repair_context: Dict[str, Any]) -> str:
    """Format repair context into a readable section for prompts.

    Args:
        repair_context: Dictionary with failed_config, validation_errors, repair_rationale

    Returns:
        Formatted repair context string
    """
    if not repair_context:
        return ""

    repair_section = "\n\n" + "="*20 + "\n"
    repair_section += "⚠️  PREVIOUS ATTEMPT FAILED - READ THIS CAREFULLY\n"

    if 'failed_config' in repair_context:
        repair_section += "FAILED OPERATOR CONFIGURATION:\n"
        repair_section += json.dumps(repair_context['failed_config'], indent=2)
        repair_section += "\n\n"

    if 'validation_errors' in repair_context:
        repair_section += "VALIDATION ERRORS:\n"
        for i, error in enumerate(repair_context['validation_errors'], 1):
            repair_section += f"{i}. {error}\n"
        repair_section += "\n"

    if 'repair_rationale' in repair_context:
        repair_section += "REPAIR GUIDANCE:\n"
        repair_section += repair_context['repair_rationale']
        repair_section += "\n\n"

    repair_section += "Please regenerate the operator configuration addressing the above errors.\n"
    repair_section += "="*20

    return repair_section
