"""
Abstract Layer Prompts
"""

from string import Template
from ..abstract.support import BaseSystem, format_operators_with_descriptions
from .instructions import get_operator_selection_rules
from typing import List

# =============================================================================
# Step 1: Operator Selection
# =============================================================================

ABSTRACT_OPERATOR_SELECTION_PROMPT = Template("""
You are an AI assistant that designs data processing pipelines using abstract operators.

Task: Analyze the query and dataset, then select appropriate abstract operators to build a pipeline.

Query: $query

Dataset Structure and Samples:
$dataset_samples

Available Abstract Operators:
$available_operators

COMPLETE EXAMPLES FROM REAL PIPELINES:

Example 1: Mining Product Reviews for Polarizing Themes
Query: "Identify polarizing themes in video game reviews that divide player opinions, resolve similar themes across reviews, and aggregate them to find common polarizing themes across different games"
Dataset: Video game reviews with fields: app_name, concatenated_reviews

Selected operators and reasoning:
- Map: identify polarizing themes from concatenated reviews (analyzes each game's reviews to find divisive topics)
- Unnest: expand polarizing_themes array into individual theme records (needed to process each theme separately)
- Resolve: deduplicate and consolidate similar themes (merges themes that are essentially the same but worded differently)
- Reduce: aggregate common themes across different games by theme (groups resolved themes to find patterns across games)

Based on the query and dataset, list the operators needed in the order they should be applied.
For each operator, provide:
- The operator type
- A brief description of what this operator will do in the pipeline

IMPORTANT:
$important_rules

Remember: Keep the pipeline simple and focused on answering the query.
""")


def get_operator_selection_prompt(
    query: str,
    dataset_samples: str,
    base_system: BaseSystem
) -> str:
    """
    Generate operator selection prompt based on base system support.

    Args:
        query: User query
        dataset_samples: Dataset samples (JSON formatted string)
        base_system: Base system type

    Returns:
        Complete prompt string
    """
    operators_info = format_operators_with_descriptions(base_system)
    rules_text = get_operator_selection_rules()
    return ABSTRACT_OPERATOR_SELECTION_PROMPT.substitute(
        query=query,
        dataset_samples=dataset_samples,
        available_operators=operators_info,
        important_rules=rules_text
    )


# =============================================================================
# Step 2: Detailed Operator Configuration Prompts
# =============================================================================

ABSTRACT_MAP_PROMPT = Template("""
Generate a Map operator configuration in abstract layer format.

A Map operator transforms EACH record independently using an LLM (1-to-1 mapping). It analyzes, summarizes, or transforms data to generate new fields. Unlike Extract, Map does NOT pull verbatim text - it performs transformations (e.g., sentiment analysis, summarization, structured extraction from analysis).

Context:
- Query: $query
- Operator Task: $operator_purpose

Available Fields (with types):
$available_fields

Last Operator:
$last_operator

Dataset Samples:
$dataset_samples

Generate a Map operator with:

1. **prompt**: A Jinja2 template string that describes the transformation
   - CRITICAL: MUST use {{ input.field_name }} to reference ALL input fields
   - Be specific about what to extract or transform
   - For each field to be output, explain the meaning of it, for example, "medication: the medication contained in the doctor's prescription in the document" is better than "medication".

2. **output**: Specify output schema as {"field1": "Type1", "field2": "Type2", ...}
   - ONLY add NEW fields generated by this operator
   - Input fields are automatically carried forward, so only list the fields you CREATE
   - Type specifications: String, Integer, Float, Boolean, List[Type], Dict{field: Type}
   - Examples: {"sentiment": "String", "scores": "List[Integer]", "metadata": "Dict{count: Integer}"}

COMPLETE EXAMPLES:

Example - Extracting structured data:
{
  "prompt": "Analyze the text: {{ input.content }}. Extract the main themes discussed. Return a list of theme names.",
  "output": {
    "themes": "List[String]",
    "summary": "String"
  },
}

IMPORTANT:
- Use ONLY available fields in input
- Make prompts specific to the task, not generic
- ALWAYS use Jinja2 format for field references: {{ input.field_name }}
""")

ABSTRACT_FILTER_PROMPT = Template("""
Generate a Filter operator configuration in abstract layer format.

A Filter operator keeps or discards records based on a condition.

Context:
- Query: $query
- Operator Task: $operator_purpose

Available Fields (with types):
$available_fields

Last Operator:
$last_operator

Dataset Samples:
$dataset_samples

Generate a Filter operator with:

1. **prompt**: A Jinja2 template that describes the filtering condition
   - MUST use {{ input.field_name }} to reference fields (Jinja2 template)
   - The prompt should ask for "true" or "false" as the response
   - Clearly state what records should PASS the filter (return true to keep)
   - Example: "Is this relevant? {{ input.title }}. Return true to keep, false to discard."

2. **input**: Specify input schema
   - {"fields": {"field1": "Type1", ...}}
   - Only include fields used in the condition
   - Example: {"fields": {"score": "Float"}}

3. **output**: Specify output schema
   - MUST include a Boolean field for the filter decision
   - Input fields are automatically carried forward, so only list the fields you CREATE
   - Type specifications: String, Integer, Float, Boolean, List[Type], Dict{field: Type}
   - Example: {"id": "Integer", "text": "String", "score": "Float", "keep": "Boolean"}

4. **properties**: Additional configuration (can be empty {})

COMPLETE EXAMPLES:

Example - Filter by relevance:
{
  "prompt": "Is this document relevant to the topic? Title: {{ input.title }}. Content: {{ input.content }}. Return true to keep this document, false to discard it.",
  "input": {"fields": {"title": "String", "content": "String"}},
  "output": {
    "title": "String",
    "content": "String",
    "keep": "Boolean"
  },
  "properties": {}
}

IMPORTANT:
- The output schema MUST have a Boolean field
- Make the filtering condition clear and specific
""")

ABSTRACT_REDUCE_PROMPT = Template("""
Generate a Reduce operator configuration in abstract layer format.

A Reduce operator aggregates/groups records by a key field.

Context:
- Query: $query
- Operator Task: $operator_purpose

Available Fields (with types):
$available_fields

Last Operator:
$last_operator

Dataset Samples:
$dataset_samples

Generate a Reduce operator with:

1. **reduce_key**: The field to group by (must exist in available fields)
   - Example: "category" (if grouping by category)

2. **prompt**: Jinja2 template describing how to aggregate
   - MUST use {{ inputs }} (plural) to reference the group of records (Jinja2 template)
   - Access fields like: {{ inputs[0].field_name }} or {% for item in inputs %}{{ item.field_name }}{% endfor %}
   - Example: "Summarize all viewpoints for theme '{{ inputs[0].theme }}': {% for item in inputs %}{{ item.viewpoint }} {% endfor %}"

3. **output**: Specify output schema
   - MUST include the reduce_key field
   - Add new aggregated fields
   - Type specifications: String, Integer, Float, Boolean, List[Type], Dict{field: Type}
   - Examples: {"category": "String", "summary": "String", "count": "Integer", "items": "List[String]"}

COMPLETE EXAMPLES:

Example - Aggregate reviews by product:
{
  "reduce_key": "product_id",
  "prompt": "Product: {{ inputs[0].product_name }}. Reviews: {% for review in inputs %}{{ review.text }}. {% endfor %}Provide: product_name: the name of the product; common_themes: a list of common themes mentioned across reviews; average_sentiment: the overall average sentiment (positive/negative/neutral).",
  "output": {
    "product_id": "String",
    "product_name": "String",
    "common_themes": "List[String]",
    "average_sentiment": "String"
  },
}

IMPORTANT:
- You MUST use {{ inputs }} (plural) to reference the group of records
- Create aggregated output schema with new field names
""")

ABSTRACT_RESOLVE_PROMPT = Template("""
Generate a Resolve operator configuration in abstract layer format.

A Resolve operator deduplicates or standardizes entities using comparison and resolution prompts.

Context:
- Query: $query
- Operator Task: $operator_purpose

Available Fields (with types):
$available_fields

Last Operator:
$last_operator

Dataset Samples:
$dataset_samples

Generate a Resolve operator with:

1. **comparison_prompt**: Jinja2 template for comparing two records
   - Uses {{ input1.field }} and {{ input2.field }} to compare two items
   - Should return "True" or "False"
   - Example: "Are {{ input1.name }} and {{ input2.name }} the same person? Return True or False."

2. **resolution_prompt**: Jinja2 template for merging records
   - Uses {{ inputs }} to merge multiple similar items
   - Describe how to create one standardized/merged record
   - Example: "Merge these person records: {% for item in inputs %}{{ item.name }}, {{ item.email }} {% endfor %}"

3. **output**: Specify output schema (resolved/standardized entity schema)
   - Type specifications: String, Integer, Float, Boolean, List[Type], Dict{field: Type}
   - Create output schema for the resolved/standardized entity

COMPLETE EXAMPLES:

Example - Resolve duplicate person names:
{
  "comparison_prompt": "Are {{ input1.name }} and {{ input2.name }} the same person? Compare their emails: {{ input1.email }} vs {{ input2.email }}. Return True if they are the same person, False otherwise.",
  "resolution_prompt": "Merge these person records: {% for item in inputs %}Name: {{ item.name }}, Email: {{ item.email }}. {% endfor %}Provide: canonical_name: the most complete/correct name; canonical_email: the primary email address.",
  "output": {
    "canonical_name": "String",
    "canonical_email": "String"
  },
}
""")

ABSTRACT_EXTRACT_PROMPT = Template("""
Generate an Extract operator configuration in abstract layer format.

An Extract operator pulls verbatim text sections from documents. It extracts exact quotes, specific text spans, or passages without transformation - the output is the original text as-is.

CRITICAL EXTRACT OPERATOR RULES:
- Extract can ONLY output a SINGLE string field containing the extracted text for each document_key
- Extract is NOT applicable for tasks needing analysis, transformation, or multiple output fields

Context:
- Query: $query
- Operator Task: $operator_purpose

Available Fields (with types):
$available_fields

Last Operator:
$last_operator

Dataset Samples:
$dataset_samples

Generate an Extract operator with:

1. **prompt**: Jinja2 template describing what text section to extract
   - Use {{ input.field }} to reference the document field
2. **document_keys**: List of field names containing the documents to extract from.

EXTRACT LOGIC (Pseudo-Python):

```python
def extract(records, prompt, document_keys):
    \"\"\"
    Extract operator internal logic:
    - Processes each record independently
    - For each document_key, extracts verbatim text using LLM
    - Creates new field with extracted content (document_key + "_extracted_findings")
    - Returns records with extracted text added as new fields
    \"\"\"
    result = []

    for record in records:
        new_record = record.copy()

        # Process each document key specified
        for doc_key in document_keys:
            if doc_key not in record:
                continue

            # Get the text content from the document field
            document_text = record[doc_key]

            # Render the extraction prompt with record data in strict Jinja2 template format.
            # Example: "Extract findings from: {{ input.content }}"
            rendered_prompt = render_template(prompt, {"input": record})

            # Use LLM to identify and extract verbatim text sections
            # LLM analyzes the document and returns exact text spans
            extracted_text = llm_extract(
                instructions=rendered_prompt,
                source_text=document_text
            )

            # Store extracted text in new field (original field + "_extracted_findings")
            output_field = f"{doc_key}_extracted_findings"
            new_record[output_field] = extracted_text  # Verbatim text

        result.append(new_record)

    return result
```

""")

ABSTRACT_UNNEST_PROMPT = Template("""
Generate an Unnest operator configuration.

An Unnest operator expands arrays or nested fields. The target of Unnest is to flatten the array or nested structure into simple types.

Context:
- Query: $query
- Operator Task: $operator_purpose

Available Fields (with types):
$available_fields

Last Operator:
$last_operator

Dataset Samples:
$dataset_samples

Generate an Unnest operator with:

1. **unnest_key**: The field name containing the array or nested structure to expand
   - Must be a field that exists in available fields: $available_fields
   - Should be a Complex type field (e.g., "List[...]]", "Dict{...}")
2. **recursive**: Whether to recursively unnest nested structures
3. **depth**: Maximum depth for recursive unnesting

UNNEST LOGIC (Pseudo-Python):

```python
def unnest(records, unnest_key, recursive=False, depth=None):
    \"\"\"
    Unnest operator internal logic:
    - If unnest_key is List: expands into multiple records (one per element)
    - If unnest_key is Dict: flattens fields to top level (same number of records)
    - If recursive=True: applies unnesting recursively up to specified `depth`
    \"\"\"
    result = []

    for record in records:
        if unnest_key not in record:
            result.append(record)
            continue

        value = record[unnest_key]
        base_record = {k: v for k, v in record.items() if k != unnest_key}

        if isinstance(value, list):
            # List: Create separate record for each element
            for item in value:
                new_record = base_record.copy()
                new_record[unnest_key] = item
                result.append(new_record)

        elif isinstance(value, dict):
            # Dict: Flatten to top level (no new records)
            new_record = base_record.copy()
            new_record.pop(unnest_key, None)
            new_record.update(value)  # Move dict fields to top level
            result.append(new_record)

        else:
            raise ValueError(f"Unnest only supports lists and dicts.")

    # If recursive and depth > 1, apply unnest again
    if recursive and depth and depth > 1:
        result = unnest(result, unnest_key, recursive=True, depth=depth-1)

    return result
```
""")

# Map of operator types to their prompts
OPERATOR_TYPE_TO_PROMPT = {
    'Map': ABSTRACT_MAP_PROMPT,
    'Filter': ABSTRACT_FILTER_PROMPT,
    'Reduce': ABSTRACT_REDUCE_PROMPT,
    'Resolve': ABSTRACT_RESOLVE_PROMPT,
    'Extract': ABSTRACT_EXTRACT_PROMPT,
    'Unnest': ABSTRACT_UNNEST_PROMPT,
    # Additional operators can be added later
}


def get_abstract_operator_prompt(
    operator_type: str,
    operator_purpose: str,
    query: str,
    dataset_samples: str,
    last_operator: str,
    available_fields: str
) -> str:
    """
    Get the appropriate prompt based on operator type.

    Args:
        operator_type: Operator type (Map, Filter, etc.)
        operator_purpose: Operator task description
        query: User query
        dataset_samples: Dataset samples
        last_operator: Last operator details (JSON string) or "None"
        available_fields: Available fields (formatted string)

    Returns:
        Complete prompt string

    Raises:
        ValueError: If operator type is not supported
    """
    prompt_template = OPERATOR_TYPE_TO_PROMPT.get(operator_type)

    if prompt_template is None:
        # For operators not yet implemented, return a generic prompt
        return f"""
Generate a {operator_type} operator configuration in abstract layer format.

Context:
- Query: {query}
- Operator Task: {operator_purpose}

Available Fields:
{available_fields}

Last Operator:
{last_operator}

Dataset Samples:
{dataset_samples}

Please generate appropriate configuration for this {operator_type} operator.
Include: input schema, output schema, and any operator-specific fields.
Return valid JSON.
"""

    return prompt_template.substitute(
        query=query,
        operator_purpose=operator_purpose,
        available_fields=available_fields,
        last_operator=last_operator,
        dataset_samples=dataset_samples
    )


# =============================================================================
# JIT Step-by-Step: Next Operator Generation
# =============================================================================

NEXT_OPERATOR_PROMPT = Template("""
You are an AI assistant that builds data processing pipelines one operator at a time.

Task: Analyze the current pipeline state and determine the NEXT operator type needed, OR decide if the pipeline is complete.

Query: $query

Dataset Structure and Samples:
$dataset_samples

Current Pipeline State:
$current_pipeline_state

Available Fields (with types):
$available_fields

Available Abstract Operators:
$available_operators

IMPORTANT RULES:
$important_rules

Your Task:
1. Analyze the query and current pipeline state
2. Determine if the pipeline is COMPLETE (query can be fully answered with current operators)
3. If COMPLETE: Return {"end": true, "reason": "explanation of why pipeline is complete"}
4. If NOT COMPLETE: Select the TYPE and PURPOSE of the NEXT operator needed

For the next operator, provide:
- type: The operator type to use (e.g., "Map", "Filter", "Reduce")
- purpose: Brief description of what this operator will do in the pipeline

Full Pipeline Examples: 

Example 1: Mining Product Reviews for Polarizing Themes
Query: "Identify polarizing themes in video game reviews that divide player opinions, resolve similar themes across reviews, and aggregate them to find common polarizing themes across different games"
Dataset: Video game reviews with fields: app_name, concatenated_reviews

Selected operators and reasoning:
- Map: identify polarizing themes from concatenated reviews (analyzes each game's reviews to find divisive topics)
- Unnest: expand polarizing_themes array into individual theme records (needed to process each theme separately)
- Resolve: deduplicate and consolidate similar themes (merges themes that are essentially the same but worded differently)
- Reduce: aggregate common themes across different games by theme (groups resolved themes to find patterns across games)

Response Format:
Either:
{"end": true, "reason": "Pipeline complete because..."}

OR:
{"end": false, "operator": {"type": "OperatorType", "purpose": "what this operator will do"}}

Remember:
- Stop when the pipeline can fully answer the query
- Each operator should have a clear purpose in the overall pipeline
""")


def get_next_operator_prompt(
    query: str,
    dataset_samples: str,
    current_pipeline_state: str,
    available_fields: str,
    base_system: BaseSystem
) -> str:
    """
    Generate prompt for JIT next operator selection and configuration.

    Args:
        query: User query
        dataset_samples: Dataset samples (JSON formatted string)
        current_pipeline_state: Current operators in pipeline (formatted string)
        available_fields: Available fields (formatted string)
        base_system: Base system type

    Returns:
        Complete prompt string
    """
    operators_info = format_operators_with_descriptions(base_system)
    rules_text = get_operator_selection_rules()

    return NEXT_OPERATOR_PROMPT.substitute(
        query=query,
        dataset_samples=dataset_samples,
        current_pipeline_state=current_pipeline_state,
        available_fields=available_fields,
        available_operators=operators_info,
        important_rules=rules_text
    )


# =============================================================================
# JIT Step-by-Step: Operator Repair
# =============================================================================

OPERATOR_REPAIR_PROMPT = Template("""
You are an AI assistant that analyzes validation errors in data processing pipelines and suggests repairs.

Query: $query

Current Pipeline:
$current_pipeline

Failed Operator (at position $operator_index):
$failed_operator

Validation Errors:
$validation_errors

Available Fields Before This Operator:
$available_fields

Your Task:
Analyze the validation errors and suggest ONE repair action to fix the pipeline.

Available Repair Actions:
1. DELETE - Remove the problematic operator entirely
2. INSERT_BEFORE - Insert a new operator BEFORE the failed operator to prepare the data
3. REPLACE - Replace the failed operator with a different operator type
4. MODIFY - Regenerate the same operator type with different configuration

Response Format (JSON):
{
  "analysis": "Brief analysis of what went wrong and why",
  "action": "DELETE|INSERT_BEFORE|REPLACE|MODIFY",
  "rationale": "Explanation of why this action will fix the error",
  "new_operator": {
    "type": "operator_type",
    "purpose": "what this operator will do"
  }  // Only needed for INSERT_BEFORE, REPLACE
}

Guidelines:
- Choose the SIMPLEST fix that addresses the validation error
- If a field is missing, consider INSERT_BEFORE to create it or MODIFY to use correct fields
- If operator type is wrong, use REPLACE
- If operator is unnecessary, use DELETE
- Provide clear rationale for your choice
""")


def get_operator_repair_prompt(
    query: str,
    current_pipeline: str,
    failed_operator: str,
    validation_errors: List[str],
    available_fields: str,
    operator_index: int
) -> str:
    """
    Generate prompt for operator repair analysis.

    Args:
        query: User query
        current_pipeline: Current pipeline state (formatted string)
        failed_operator: Failed operator configuration (JSON string)
        validation_errors: List of validation error messages
        available_fields: Available fields (formatted string)
        operator_index: Index of failed operator

    Returns:
        Complete prompt string
    """
    errors_text = "\n".join(f"- {error}" for error in validation_errors)

    return OPERATOR_REPAIR_PROMPT.substitute(
        query=query,
        current_pipeline=current_pipeline,
        failed_operator=failed_operator,
        validation_errors=errors_text,
        available_fields=available_fields,
        operator_index=operator_index
    )
